on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: 'Version number for the release'
      dry_run:
        type: boolean
        required: true
        default: true
        description: 'Run the release in dry run mode, without pushing any changes'

name: Manually trigger a release

jobs:
  release:
    name: Trigger a release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.EXPO_BOT_PAT }}
      INPUT_VERSION: ${{ github.event.inputs.version }}
      INPUT_DRY_RUN: ${{ github.event.inputs.dry_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.EXPO_BOT_PAT }}
      - uses: ./.github/actions/setup-mise
      - run: |
          # Lerna will not detect changes correctly without having all tags
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          # Checkout the main branch
          git checkout main
          git config --global user.email "support+ci@expo.io"
          git config --global user.name "Expo CI"
          yarn install --frozen-lockfile --check-files
          yarn build
          if [[ "$INPUT_VERSION" == "" ]]; then
            echo "Releasing with default version"
            yarn release
          else
            echo "Releasing with version $INPUT_VERSION"
            yarn release $INPUT_VERSION
          fi
